In [1]:
import pandas as pd

In [3]:
columns = [
    'stitch_id_flat',
    'stitch_id_sterio',
    'umls_cui_from_label',
    'meddra_type',
    'umls_cui_from_meddra',
    'side_effect_name',
]
se_df = pd.read_table("download/meddra_all_se.tsv.gz", names = columns)
se_df

,stitch_id_flat,stitch_id_sterio,umls_cui_from_label,meddra_type,umls_cui_from_meddra,side_effect_name
0,CID100000085,CID000010917,C0000729,LLT,C0000729,Abdominal cramps
1,CID100000085,CID000010917,C0000729,PT,C0000737,Abdominal pain
2,CID100000085,CID000010917,C0000737,LLT,C0000737,Abdominal pain
3,CID100000085,CID000010917,C0000737,PT,C0687713,Gastrointestinal pain
4,CID100000085,CID000010917,C0000737,PT,C0000737,Abdominal pain
...,...,...,...,...,...,...
309844,CID171306834,CID071306834,C3203358,PT,C1145670,Respiratory failure
309845,CID171306834,CID071306834,C3665386,LLT,C3665386,Abnormal vision
309846,CID171306834,CID071306834,C3665386,PT,C3665347,Visual impairment
309847,CID171306834,CID071306834,C3665596,LLT,C3665596,Warts
309848,CID171306834,CID071306834,C3665596,PT,C0347390,Skin papilloma

In [4]:
columns = [
    'stitch_id_flat',
    'umls_cui_from_label',
    'method',
    'concept_name',
    'meddra_type',
    'umls_cui_from_meddra',
    'meddra_name',
]
indication_df = pd.read_table("download/meddra_all_indications.tsv.gz", names = columns)
indication_df

,stitch_id_flat,umls_cui_from_label,method,concept_name,meddra_type,umls_cui_from_meddra,meddra_name
0,CID100000085,C0015544,text_mention,Failure to Thrive,LLT,C0015544,Failure to thrive
1,CID100000085,C0015544,text_mention,Failure to Thrive,PT,C0015544,Failure to thrive
2,CID100000085,C0020615,text_mention,Hypoglycemia,LLT,C0020615,Hypoglycaemia
3,CID100000085,C0020615,text_mention,Hypoglycemia,PT,C0020615,Hypoglycaemia
4,CID100000085,C0022661,NLP_indication,"Kidney Failure, Chronic",LLT,C0022661,Renal failure chronic
...,...,...,...,...,...,...,...
30830,CID171306834,C0524910,NLP_precondition,"Hepatitis C, Chronic",PT,C0524910,Chronic hepatitis C
30831,CID171306834,C0741132,text_mention,Antibody test positive,LLT,C0741132,Antibody test positive
30832,CID171306834,C0741132,text_mention,Antibody test positive,PT,C0741132,Antibody test positive
30833,CID171306834,C0856536,text_mention,Philadelphia chromosome positive,LLT,C0856536,Philadelphia chromosome positive
30834,CID171306834,C0856536,text_mention,Philadelphia chromosome positive,PT,C0476431,Chromosome analysis abnormal

In [5]:
all_se_df = pd.read_table("download/meddra_all_label_indications.tsv.gz")
all_se_df

,EMA/WC500020092.html,CID100216416,CID000216416,C0016658,NLP_indication,Fracture,LLT,C0016658.1,Fracture.1
0,EMA/WC500020092.html,CID100216416,CID000216416,C0016658,NLP_indication,Fracture,PT,C0016655,Multiple fractures
1,EMA/WC500020092.html,CID100216416,CID000216416,C0016658,NLP_indication,Fracture,PT,C0016658,Fracture
2,EMA/WC500020092.html,CID100216416,CID000216416,C0019557,NLP_indication,Hip Fractures,LLT,C0019557,Hip fracture
3,EMA/WC500020092.html,CID100216416,CID000216416,C0019557,NLP_indication,Hip Fractures,PT,C0019557,Hip fracture
4,EMA/WC500020092.html,CID100216416,CID000216416,C0029456,NLP_indication,Osteoporosis,LLT,C0029456,Osteoporosis
...,...,...,...,...,...,...,...,...,...
447144,safety/2008_-_May_PI_-_Vfend_PI.html,CID100071616,CID000071616,C0239295,NLP_precondition,Oesophageal candidiasis,PT,C0239295,Oesophageal candidiasis
447145,safety/2008_-_May_PI_-_Vfend_PI.html,CID100071616,CID000071616,C0376545,NLP_precondition,Hematologic Neoplasms,LLT,C0376545,Haematological malignancy
447146,safety/2008_-_May_PI_-_Vfend_PI.html,CID100071616,CID000071616,C0376545,NLP_precondition,Hematologic Neoplasms,PT,C0376545,Haematological malignancy
447147,safety/2008_-_May_PI_-_Vfend_PI.html,CID100071616,CID000071616,C0877445,NLP_precondition,Candidemia,LLT,C0877445,Candidemia
447148,safety/2008_-_May_PI_-_Vfend_PI.html,CID100071616,CID000071616,C0877445,NLP_precondition,Candidemia,PT,C0153252,Systemic candida

In [8]:
columns = [
    'reference_url', # an approximate name - not sure what exactly it is
    'stitch_id_flat',
    'stitch_id_sterio',
    'umls_cui_from_label',
    'method',
    'concept',
    'meddra_type',
    'umls_cui_from_meddra',
    'meddra_name',
]
all_indication_df = pd.read_table("download/meddra_all_label_indications.tsv.gz", names = columns)
all_indication_df

,reference_url,stitch_id_flat,stitch_id_sterio,umls_cui_from_label,method,concept,meddra_type,umls_cui_from_meddra,meddra_name
0,EMA/WC500020092.html,CID100216416,CID000216416,C0016658,NLP_indication,Fracture,LLT,C0016658,Fracture
1,EMA/WC500020092.html,CID100216416,CID000216416,C0016658,NLP_indication,Fracture,PT,C0016655,Multiple fractures
2,EMA/WC500020092.html,CID100216416,CID000216416,C0016658,NLP_indication,Fracture,PT,C0016658,Fracture
3,EMA/WC500020092.html,CID100216416,CID000216416,C0019557,NLP_indication,Hip Fractures,LLT,C0019557,Hip fracture
4,EMA/WC500020092.html,CID100216416,CID000216416,C0019557,NLP_indication,Hip Fractures,PT,C0019557,Hip fracture
...,...,...,...,...,...,...,...,...,...
447145,safety/2008_-_May_PI_-_Vfend_PI.html,CID100071616,CID000071616,C0239295,NLP_precondition,Oesophageal candidiasis,PT,C0239295,Oesophageal candidiasis
447146,safety/2008_-_May_PI_-_Vfend_PI.html,CID100071616,CID000071616,C0376545,NLP_precondition,Hematologic Neoplasms,LLT,C0376545,Haematological malignancy
447147,safety/2008_-_May_PI_-_Vfend_PI.html,CID100071616,CID000071616,C0376545,NLP_precondition,Hematologic Neoplasms,PT,C0376545,Haematological malignancy
447148,safety/2008_-_May_PI_-_Vfend_PI.html,CID100071616,CID000071616,C0877445,NLP_precondition,Candidemia,LLT,C0877445,Candidemia
447149,safety/2008_-_May_PI_-_Vfend_PI.html,CID100071616,CID000071616,C0877445,NLP_precondition,Candidemia,PT,C0153252,Systemic candida

In [10]:
all_indication_df[all_indication_df['stitch_id_flat'] != all_indication_df['stitch_id_sterio']]

,reference_url,stitch_id_flat,stitch_id_sterio,umls_cui_from_label,method,concept,meddra_type,umls_cui_from_meddra,meddra_name
0,EMA/WC500020092.html,CID100216416,CID000216416,C0016658,NLP_indication,Fracture,LLT,C0016658,Fracture
1,EMA/WC500020092.html,CID100216416,CID000216416,C0016658,NLP_indication,Fracture,PT,C0016655,Multiple fractures
2,EMA/WC500020092.html,CID100216416,CID000216416,C0016658,NLP_indication,Fracture,PT,C0016658,Fracture
3,EMA/WC500020092.html,CID100216416,CID000216416,C0019557,NLP_indication,Hip Fractures,LLT,C0019557,Hip fracture
4,EMA/WC500020092.html,CID100216416,CID000216416,C0019557,NLP_indication,Hip Fractures,PT,C0019557,Hip fracture
...,...,...,...,...,...,...,...,...,...
447145,safety/2008_-_May_PI_-_Vfend_PI.html,CID100071616,CID000071616,C0239295,NLP_precondition,Oesophageal candidiasis,PT,C0239295,Oesophageal candidiasis
447146,safety/2008_-_May_PI_-_Vfend_PI.html,CID100071616,CID000071616,C0376545,NLP_precondition,Hematologic Neoplasms,LLT,C0376545,Haematological malignancy
447147,safety/2008_-_May_PI_-_Vfend_PI.html,CID100071616,CID000071616,C0376545,NLP_precondition,Hematologic Neoplasms,PT,C0376545,Haematological malignancy
447148,safety/2008_-_May_PI_-_Vfend_PI.html,CID100071616,CID000071616,C0877445,NLP_precondition,Candidemia,LLT,C0877445,Candidemia
447149,safety/2008_-_May_PI_-_Vfend_PI.html,CID100071616,CID000071616,C0877445,NLP_precondition,Candidemia,PT,C0153252,Systemic candida